### ISSUE TITLE
Sonoff Mini R2 OTA flash

### ISSUE THREAD

**Issue by federicochiesa** [itead/Sonoff_Devices_DIY_Tools#110]
I just bought a Sonoff Mini R2 and it says it's in Diy mode by default. The problem is that it doesn't connect to the sonoffDiy network for the OTA flash. How do I solve this?

**Comment by rraat** [comment]
If you just bought it it's probably running the new DIY variant. Check out the following URL

https://github.com/itead/Sonoff_Devices_DIY_Tools/blob/master/SONOFF%20DIY%20MODE%20Protocol%20Doc%20v2.0%20Doc.pdf

**Comment by federicochiesa** [comment]
Yes, that was the way to do it! Thanks.
