### ISSUE TITLE
Feature Request: Improve responsiveness of UI/API by changing mDNS browse thread to use callback feature in Zeroconf

### ISSUE THREAD

**Issue by mattsaxon** [itead/Sonoff_Devices_DIY_Tools#2]
I've noticed that the Zeroconf implementation doesn't allow notification and as a result this code must to a busy polling (currently every 0.5s).

In an effort to improve the responsiveness of this code, I've submitted a draft PR to improve Zeroconf here for this purpose. https://github.com/jstasiak/python-zeroconf/pull/166

I though you would be interested.

**Comment by ZZLinvec** [comment]
Thank you very much，I will follow up later.

**Comment by mattsaxon** [comment]
The PR has not been accepted (https://github.com/jstasiak/python-zeroconf/pull/166) so is in latest copy of branch, though PyPi is yet to include this update.

**Comment by mattsaxon** [comment]
PyPi now has this change under release 0.23.0 https://pypi.org/project/zeroconf/0.23.0/

**Comment by ZZLinvec** [comment]
nice
