### ISSUE TITLE
How can I flash other eWeLink devices?

### ISSUE THREAD

**Issue by marrobHD** [itead/Sonoff_Devices_DIY_Tools#20]
How can I flash other eWeLink devices? Please help me to flash my outdoor socket.

**Comment by ZZLinvec** [comment]
My tool is a simple dome.Some functionality is implemented around the API.Check out the API documentation if you have more ideas.It may be of some help to you.

**Comment by alexandre-mbm** [comment]
I would to know if we can to make hacking in the Sonoff RF to turn it on "a DIY Mode device" such as the Sonoff Mini.

**Comment by marrobHD** [comment]
I flashed it over usb serial interface back then.
