### ISSUE TITLE
Trojan:Win32/Fuery.C!cl in exe file???

### ISSUE THREAD

**Issue by cHunter789** [itead/Sonoff_Devices_DIY_Tools#27]
HI I have tried to run tool_01DIY85(3.3.0).exe but Windows Defender has blocked the file and warning about Trojan:Win32/Fuery.C!cl False alarm or wtf?

**Comment by rradar** [comment]
Here is what other snake oil tells @cHunter789 

https://www.virustotal.com/gui/file/35e67cbe0da26731f2efe10fec4e5e085093c02279167996da2e27e953a42e8e/detection

**Comment by cHunter789** [comment]
Today Windows Defender not detecting this anymore. Looks like false alarm. Closing.

**Comment by herbbetz** [comment]
same issue on my Win10 today (23 Aug, 2019)
