### ISSUE TITLE
WiFi SSID and Password Setting

### ISSUE THREAD

**Issue by alexbk66** [itead/Sonoff_Devices_DIY_Tools#29]
Another question - it's a nice feature to be able to set WiFi SSID and Password using REST API, but I don't understand how it can be used - because to use REST API the device **must** be already connected to WiFi?

So my understanding is - this command can be only used when device is connected to "old" wifi **before** switching to new one?

**Comment by ZZLinvec** [comment]
yes

**Comment by alexbk66** [comment]
Thank you
