### ISSUE TITLE
Device type field

### ISSUE THREAD

**Issue by alexbk66** [itead/Sonoff_Devices_DIY_Tools#31]
Minor problem: the protocol returns device type "diy_plug" for all devices.  Should it instead return the real type, i.e. "BASICR3"?  In case the protocol will be different for different devices, and also to be able to display the correct device type in the client app?

**Comment by ZZLinvec** [comment]
There is such a problem.I'd like to hear your valuable advice.

**Comment by alexbk66** [comment]
@ZZLinvec  If you need any help - let me know

**Comment by alexbk66** [comment]
@ZZLinvec why is it closed - is it fixed?
