### ISSUE TITLE
DIY tool doesnt find my Sonoff mini

### ISSUE THREAD

**Issue by dastrix80** [itead/Sonoff_Devices_DIY_Tools#35]
Jumper mode set, ssid sonoffDiy created with password set. The tool does not see the device, no matter what I try, including public/private mode

Any suggestions?

**Comment by ZZLinvec** [comment]
Suggest you check the computer network card is a dual network card

**Comment by dastrix80** [comment]
Done that, all disabled except wifi

Checked the sonoffDiy SSID and i dont see the mini connected..

**Comment by ZZLinvec** [comment]
Is the mini version 3.3.0?After operating the network needs to reopen the software

**Comment by dastrix80** [comment]
Yes, its 3.3

Sorry, that didnt make any sense. After operating the network needs to reopen the software>

The issue so far isnt the software, i cant see the sonoff mini connect to the sonoffDiy SSID.

**Comment by ZZLinvec** [comment]
What is the wifi status light on the device?

**Comment by ZZLinvec** [comment]
Single flash or double flash？

**Comment by dastrix80** [comment]
Its a single flash

**Comment by ZZLinvec** [comment]
This must be because wifi is not connected. It is suggested to check whether wifi is too far away from the device, and then check whether the SSID and password of wifi are wrong

**Comment by dastrix80** [comment]
its about 2 meters away. Yep, its not connected as indicated by the unifi wireless output

This is my wifi setup

![image](https://user-images.githubusercontent.com/38266552/63502002-f5c4af80-c50f-11e9-9910-40a968dd7d8e.png)

**Comment by dastrix80** [comment]
Now its flashing 3 times

**Comment by ZZLinvec** [comment]
I suggest you go to our after-sale service. It should be the damaged equipment

**Comment by dastrix80** [comment]
I doubt it. Ive got 4, they all do the same thing.

**Comment by ZZLinvec** [comment]
You can test it to see if it doesn't work with sonoffDiy

**Comment by davecoutts** [comment]
It looks from the screenshot that you have a Ubiquiti Access Point. I found that I could not get pairing to work via my Ubiquiti AP if the sonoffDiy SSID was radiating on both the 2G and 5G WiFi bands. I got pairing to work by disabling the 5G band on the sonoffDiy SSID. Setup the sonoffDiy SSID as normal/defaults and then go to the WLANS config section of the AP and disable the 5G band for the sonoffDiy SSID. Oddly the Mini works fine on dual band SSIDs once you have it setup. It was just eWeLink pairing that had an issue with a dual band SSID, in my case.

**Comment by ferry133** [comment]
Same fail situation for my 2 Sonoff minis. I have tried the iphone hotspot (cannot disable 5 ghz) and and dedicate Unifi 2.4 Ghz sonoffDiy SSID, both of them are failed to find my Sonoff minis when launched the DIY tool. Has upgraded ewelink firmware to 3.3.0 and confirmed both win10 and minis connected to sonoffDiy (blue indicator blinks 2 times/sec & sonoffDiy client list in the Unifi). Any recommendation?

**Comment by davecoutts** [comment]
Hi ferry133

Here is a screenshot of the 5G band disabled as an override in the WLAN setting section of the UniFi Access Point(AP). Is your AP set the same? 

![sonoffDiy_5G_off](https://user-images.githubusercontent.com/484306/67158805-b4485900-f334-11e9-885c-6f7488873a0e.png)

**Comment by ferry133** [comment]
Hi, davecoutts, thanks for help.
Not exactly the same with your setting. I created another WLAN1 with sonoffDiy SSID and enable it only on 2.4GHz. 

![螢幕快照 2019-10-20 下午7 40 10](https://user-images.githubusercontent.com/55702501/67159031-f348cf80-f371-11e9-9c1f-7d2710a318d0.png)

**Comment by davecoutts** [comment]
I agree. That should give the same result as my UniFi setup.
Maybe as an elimination step try setting up a duel 2G+5G network in the default WLAN and then disable 5G in the WLAN section, as worked in my case. 
I'm clutching at straws but there may be a an expected configuration quirk with the Ubiquiti or Sonoff Mini software.

My Mini would not tether to the sonoffDiy SSID(2G WiFi only) on my Android phone when other devices would. So the Mini in pre-DIY upgrade state appears to be very particular about the WiFi network it will attach to.

Below are my Ubiquiti component versions and a screenshot of the sonoffDiy network settings in case its of any help.

AP Model:  UniFi AP-AC-Pro
AP Version:  4.0.54.10625
AP Board Revision:  26
UniFi Controller:  5.11.50.0

![sonoffDiy_wireless_networks_setting](https://user-images.githubusercontent.com/484306/67159820-c4b30080-f341-11e9-8918-5581f422f6c4.png)

I will also mention that I could not get the Sonoff DIY tool to run. It failed to run with dependency errors. I did have success with the [Tasmota manual-flash](https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-DIY#manual-flash) method on Linux.

**Comment by ferry133** [comment]
Thanks a lot. I’d better try the manual way.

**Comment by ferry133** [comment]
It's work for the [Tasmota manual-flash](https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-DIY#manual-flash) method on Mac, too. 
Many thanks for davecoutts' sharing.

**Comment by vjversatile** [comment]
I figured that the firmware on the sonoff needs to be the latest version (3.3 +) before the diy mode password and ssid work. did the itead ewelink pairing, it prompted to upgrade firmware, upgraded and then tried the steps for DIY mode and they worked.

**Comment by ferry133** [comment]
I had upgraded ewelink 3.3 before trying DIY tool but not work, in my case, and I'm not alone. You may check others' case including Sonoff R3. I finally solved it by manual-flash way.

**Comment by andylebedev** [comment]
this way not working for new sonoff mini v 1.2 based on 2019.06.25 it comes loaded with 3.3.0 and tool does not recognize sonoff

i can see sonoff connected to network and i can ping it
![image](https://user-images.githubusercontent.com/38136612/68614067-d7e06880-04c8-11ea-8b32-3991fd202dcd.png)
![20191111_211917](https://user-images.githubusercontent.com/38136612/68614175-124a0580-04c9-11ea-82fa-2c76a453f2b8.jpg)
![Screenshot_20191111-211823_Settings](https://user-images.githubusercontent.com/38136612/68614177-124a0580-04c9-11ea-8cca-9e16c484ea5a.jpg)
