### ISSUE TITLE
DIY mode flashing stuck at 0% with internet access

### ISSUE THREAD

**Issue by dastrix80** [itead/Sonoff_Devices_DIY_Tools#44]
Hi All, using latest firmware on the Mini and have managed to connect it off the sonoffDiy SSID and onto my home WIFI network.

I can ping it just fine. When I select the sonoff-basic.bin file, it's stuck at 0%

All other devices on my network are operating fine and have internet access, yet this is stuck at 0% indefinitely.

Can anyone please assist? It appears a bug in the tool which is V1.2.0

Thanks

**Comment by dastrix80** [comment]
In the log, I can see it trying
 downloadURL as http://192.168.0.66:776/i/itead.bin

Yet the file name im using is not itead.bin, .66 is the right IP of the DIY Tool machine

**Comment by sgupta999** [comment]
I am having the same issue - how did you resolve it?
Can't flash it
