### ISSUE TITLE
Sonoff conected to DIY TOOL but "ERROR: Please check your network connection"

### ISSUE THREAD

**Issue by dawidtelepski** [itead/Sonoff_Devices_DIY_Tools#48]
Hi 
Sonoff mini v3.3 
Hotspot on huawei mobile phone
DIY tool is working,  
Device is connected to hotspot and visible on DIY Tool. 
One Wifi card on laptop (ethernet turned off) 

But when I want to do something (turn Relay ON/OFF) or change SSID/psswd I got 

"ERROR: Please check your network connection"
Does someone had the same issue?

**Comment by zenzbert** [comment]
hi,

run into the same issue. i have tried several networks (raspberry pi network, mobile hotspot, wifi router, wifi router guest access, ...) always got the same error: Please check your network connection and retry.！

how did you solve your problem?
