### ISSUE TITLE
Undocumented field 'selfApikey'

### ISSUE THREAD

**Issue by mattsaxon** [itead/Sonoff_Devices_DIY_Tools#5]
The PDF document doesn't reference this key, but it is in the tool implementation (dummy data by the looks of it ('123').

The eWeLink iOS app also send this field, but a more real looking one in GUID format

What is this field for given that it is not the apiKey of the device itself?

**Comment by ZZLinvec** [comment]
When the device is in DIY mode, we don't have to worry too much about this field and the encrypted field.
Because we're in DIY mode, we don't have encrypted information.

**Comment by mattsaxon** [comment]
Understood, I can get it working simply by using a dummy value, but the API shouldn't really need it if it is not needed

**Comment by ZZLinvec** [comment]
YES
