### ISSUE TITLE
Sending in invalid or unexpected JSON locks up device

### ISSUE THREAD

**Issue by frenck** [itead/Sonoff_Devices_DIY_Tools#53]
Sending an invalid payload, causes the internal webserver of the Sonoff to get stuck/hang.

Examples:

![image](https://user-images.githubusercontent.com/195327/68413766-2d4a0c00-018f-11ea-96f9-db4f0137b647.png)

![image](https://user-images.githubusercontent.com/195327/68413798-42bf3600-018f-11ea-8371-659c5942e0b7.png)

It eventually times out.

What should have happened in my opinion: Respond instantly with an error code.

**Comment by Daniel-zhan-itead** [comment]
Agree, this issue will be fixed in the next firmware.

**Comment by frenck** [comment]
Great 👍

**Comment by Daniel-zhan-itead** [comment]
issue has been fixed in firmware of 3.5.0

**Comment by frenck** [comment]
🎉
