### ISSUE TITLE
Please add `bssid` to `zeroconf/info` call

### ISSUE THREAD

**Issue by frenck** [itead/Sonoff_Devices_DIY_Tools#57]
This is a feature request for adding the `bssid` to the `zeroconf/info` call.

It is very normal to have multiple access points in a home these days (e.g., UniFi gear). With only the SSID, you can't tell to which AP the device is connected.

**Comment by Daniel-zhan-itead** [comment]
Sonoff is evaluating this request, will update you.

**Comment by Daniel-zhan-itead** [comment]
Hi Frenck,

the bssid also has been added in zeroconf/info for the new DIY Mode.

Daniel

**Comment by frenck** [comment]
👍 Awesome, thanks 👍
