### ISSUE TITLE
Sonoff DIY arrived with encryption enabled!

### ISSUE THREAD

**Issue by mattsaxon** [itead/Sonoff_Devices_DIY_Tools#6]
Just got my first Sonoff DIY in the post.

It's the new R3 body style!

Imagine my surprise when it as v2.6.1 firmware install, and eWeLink reports it as a Sonoff RF

When I upgraded its firmware to V3, it came down as v3.1.0 (newer, my other devoces have 3.0.1 max).

This tool can see the device as the type reported in the TXT record is "plug", not "diyplug". Even if I change this, the tool won't work with it as encryption is on!

**Comment by ZZLinvec** [comment]
Do not enter DIY mode until the device is upgraded to 3.1.0.When you go into DIY mode, it's "diyplug"

**Comment by mattsaxon** [comment]
Thanks, I've put the device in DIY mode using the jumper switch and now it is behaving as expected.
