### ISSUE TITLE
Sonoff DIY Basic R3

### ISSUE THREAD

**Issue by diogoribeiro09** [itead/Sonoff_Devices_DIY_Tools#89]
Hi,
I got a brand new Sonoffy DID Basic R3 and i was never able to connect it to eWelink or flash it with tasmota. Tried both quick pairing and compatible pairing and i made sure i was on a 2.4ghz network. Weird enough though, the device shows up on my UDM-pro and has a valid ip.
![Image](https://images-ext-1.discordapp.net/external/Tt5fQXAiAz5MZfBeIQIPRYHGzl4PgovLZ_FgdIm0BtY/https/i.imgur.com/Olf823u.png?width=1442&height=32)
 I can ping it and it replies back. The thing is : it is blinking as it is not connected. Any suggestion ?

**Comment by dzek69** [comment]
try resetting the device and pairing again with another mobile phone -- i spent an hour pairing my device until it randomly worked

or just flash it with something else (tasmota?) using soldering way

**Comment by diogoribeiro09** [comment]
> try resetting the device and pairing again with another mobile phone -- i spent an hour pairing my device until it randomly worked
> 
> or just flash it with something else (tasmota?) using soldering way

Yeah, that was the only way i got it working. I don't know why i couldn't do it on 3 different phones, 2 different networks.
